### PR TITLE
Enable tests against multiple ActiveSupport versions

### PR DESCRIPTION
**Pull request by yevgenko**
Can be merged after https://github.com/veeqo/mws-rb/pull/17

### CODE REVIEW

**Comment by DanielVartanov** [comment]
:+1:

**Comment by yevgenko** [comment]
Ok, this is expected, two failed and one green, seems like the problem introduced in latest versions of 4.1 and 4.2, because it fails with identical error. Perhaps I had older version of 4.1 and that's why it is not failed.

**Comment by yevgenko** [comment]
@DanielVartanov I'm done, can be merged after https://github.com/veeqo/mws-rb/pull/17
But we only interested in d5c4df4, I can rebase once #17 is merged

**Comment by stjhimy** [comment]
@yevgenko indeed, replacing `require 'active_support/core_ext` to `require 'active_support/all'` fixed the issue for 4.1.x and 4.2.x

**Comment by yevgenko** [comment]
Hey @stjhimy, the only missing part was `require 'active_support'` just above core, unless you're looking to use more components of it.

Here is a bit more details (in commit description): https://github.com/veeqo/mws-rb/pull/17/commits/2862c7d9a7a13953db476e8bfcf4ac4429f5c64d

p.s.
I have another PR #17 for fixing AS issue and this one is simply to enable Travis-CI to run tests agains different versions ;)

**Comment by stjhimy** [comment]
@yevgenko beautiful! thanks!

**Pull request merged**
